name: "Linter"

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install black
      - run: |
          black --version
          black --check --diff .


